# This is a config for E2B sandbox template.
# You can use template ID (0b5m4ijc6tsskrud8dvh) or template name (opencode-final) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("opencode-final") # Sync sandbox
# sandbox = await AsyncSandbox.create("opencode-final") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('opencode-final')

team_id = "711cb996-8c5b-4ce9-a82f-ff42f348d53f"
dockerfile = "e2b.Dockerfile"
template_name = "opencode-final"
template_id = "0b5m4ijc6tsskrud8dvh"
